//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBL {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserGRBL.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right click here to add custom buttons.
        /// </summary>
        internal static string AddCustomButtonsHint {
            get {
                return ResourceManager.GetString("AddCustomButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file is already loading, please wait....
        /// </summary>
        internal static string AlreadyLoading {
            get {
                return ResourceManager.GetString("AlreadyLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abort current job?.
        /// </summary>
        internal static string BoxAbortProgramConfirm {
            get {
                return ResourceManager.GetString("BoxAbortProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic update failed!
        ///Please manually download the new version from lasergrbl site..
        /// </summary>
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update require administrator privilege!.
        /// </summary>
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update result.
        /// </summary>
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update success!.
        /// </summary>
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are some changes that have not been applied.
        ///Do you want to rewrite the configuration?.
        /// </summary>
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changes detected!.
        /// </summary>
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot connect to device.
        /// </summary>
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide GCode commands.
        /// </summary>
        internal static string BoxCustomButtonPleaseGCodeText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseGCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide tooltip text.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing field.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipTitle {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to delete selected button?.
        /// </summary>
        internal static string BoxDeleteCustomButtonText {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete custom button.
        /// </summary>
        internal static string BoxDeleteCustomButtonTitle {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error exporting config!.
        /// </summary>
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File does not exist!.
        /// </summary>
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config exported successfully!.
        /// </summary>
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error reading file!.
        /// </summary>
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config imported with {1} errors!.
        /// </summary>
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config imported successfully!.
        /// </summary>
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import custom button.
        /// </summary>
        internal static string BoxImportCustomButtonCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove actual buttons? Select yes to remove, no to keep..
        /// </summary>
        internal static string BoxImportCustomButtonClearText {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string BoxImportCustomButtonrCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The engraver has some configuration parameters out of range. Please check machine configuration (menu &quot;Grbl&quot;, &quot;Grbl Configuration&quot;) parameters 130 and 131..
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeText {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeTitle {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error reading config!.
        /// </summary>
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing cached values....
        /// </summary>
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config read successfully!.
        /// </summary>
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test notification has been sent, please check your phone!.
        /// </summary>
        internal static string BoxTelegramSettingText {
            get {
                return ResourceManager.GetString("BoxTelegramSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Telegram notification.
        /// </summary>
        internal static string BoxTelegramSettingTitle {
            get {
                return ResourceManager.GetString("BoxTelegramSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No changes... nothing to write!.
        /// </summary>
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config written with {1} errors!.
        /// </summary>
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Config written successfully!.
        /// </summary>
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect.
        /// </summary>
        internal static string BtnConnectTT {
            get {
                return ResourceManager.GetString("BtnConnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        internal static string BtnDisconnectTT {
            get {
                return ResourceManager.GetString("BtnDisconnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear drawing....
        /// </summary>
        internal static string ClearDrawing {
            get {
                return ResourceManager.GetString("ClearDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit button.
        /// </summary>
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove button.
        /// </summary>
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems that your computer does not support software rendering.
        ///Do you want to restart LaserGRBL and switch to legacy mode?.
        /// </summary>
        internal static string DBOIssueSuggestGDI {
            get {
                return ResourceManager.GetString("DBOIssueSuggestGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diagonal (old).
        /// </summary>
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal (old).
        /// </summary>
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross Fill.
        /// </summary>
        internal static string DirectionNewCross {
            get {
                return ResourceManager.GetString("DirectionNewCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diagonal.
        /// </summary>
        internal static string DirectionNewDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diagonal Cross Fill.
        /// </summary>
        internal static string DirectionNewDiagonalCross {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diagonal Grid.
        /// </summary>
        internal static string DirectionNewDiagonalGrid {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grid.
        /// </summary>
        internal static string DirectionNewGrid {
            get {
                return ResourceManager.GetString("DirectionNewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hilbert.
        /// </summary>
        internal static string DirectionNewHilbert {
            get {
                return ResourceManager.GetString("DirectionNewHilbert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal.
        /// </summary>
        internal static string DirectionNewHorizontal {
            get {
                return ResourceManager.GetString("DirectionNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inset Filling.
        /// </summary>
        internal static string DirectionNewInsetFilling {
            get {
                return ResourceManager.GetString("DirectionNewInsetFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diagonal Reversed.
        /// </summary>
        internal static string DirectionNewReverseDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewReverseDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Squares.
        /// </summary>
        internal static string DirectionNewSquares {
            get {
                return ResourceManager.GetString("DirectionNewSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical.
        /// </summary>
        internal static string DirectionNewVertical {
            get {
                return ResourceManager.GetString("DirectionNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zig Zag.
        /// </summary>
        internal static string DirectionNewZigZag {
            get {
                return ResourceManager.GetString("DirectionNewZigZag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Filling.
        /// </summary>
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical (old).
        /// </summary>
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File transfer in progress. Disconnect anyway?.
        /// </summary>
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dithering Options.
        /// </summary>
        internal static string DitheringOptions {
            get {
                return ResourceManager.GetString("DitheringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File transfer in progress. Exit anyway?.
        /// </summary>
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems that your computer does not support hardware acceleration.
        ///Do you want to restart LaserGRBL and switch to software rendering?.
        /// </summary>
        internal static string FBOIssueSuggestDBO {
            get {
                return ResourceManager.GetString("FBOIssueSuggestDBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart required.
        /// </summary>
        internal static string FirmwareRequireRestart {
            get {
                return ResourceManager.GetString("FirmwareRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart is required to apply Firmware type changes. Restart now?.
        /// </summary>
        internal static string FirmwareRequireRestartNow {
            get {
                return ResourceManager.GetString("FirmwareRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpticalCorrect.
        /// </summary>
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SimpleAverage.
        /// </summary>
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WeightAverage.
        /// </summary>
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart is required to apply icons changes. Restart now?.
        /// </summary>
        internal static string IconsChangesRequiresRestart {
            get {
                return ResourceManager.GetString("IconsChangesRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smooth (HQ Bicubic).
        /// </summary>
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharp (NearestNeighbor).
        /// </summary>
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart required.
        /// </summary>
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Require application restart, restart now?.
        /// </summary>
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line To Line Options.
        /// </summary>
        internal static string Line2LineOptions {
            get {
                return ResourceManager.GetString("Line2LineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alarm.
        /// </summary>
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecting.
        /// </summary>
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Door.
        /// </summary>
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hold.
        /// </summary>
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Idle.
        /// </summary>
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jog.
        /// </summary>
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estimated Time:.
        /// </summary>
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projected Time:.
        /// </summary>
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MDI Icon code.
        /// </summary>
        internal static string MdiIconCaption {
            get {
                return ResourceManager.GetString("MdiIconCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot open a new file now..
        /// </summary>
        internal static string MsgboxCannotOpenFileNow {
            get {
                return ResourceManager.GetString("MsgboxCannotOpenFileNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prepare drawing....
        /// </summary>
        internal static string PrepareDrawing {
            get {
                return ResourceManager.GetString("PrepareDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart is required to apply preview changes. Restart now?.
        /// </summary>
        internal static string PreviewChangesRequiresRestart {
            get {
                return ResourceManager.GetString("PreviewChangesRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error connecting your engraver.
        ///If you need help click on &quot;?&quot; button..
        /// </summary>
        internal static string ProblemConnectingText {
            get {
                return ResourceManager.GetString("ProblemConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with connection?.
        /// </summary>
        internal static string ProblemConnectingTitle {
            get {
                return ResourceManager.GetString("ProblemConnectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems that the current position is no longer known by Grbl.
        ///Without the Homing Procedure ($H) the result may not be reliable.
        ///Continue anyway?.
        /// </summary>
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown position.
        /// </summary>
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed:.
        /// </summary>
        internal static string SpeedSliderToolTip {
            get {
                return ResourceManager.GetString("SpeedSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step:.
        /// </summary>
        internal static string StepSliderToolTip {
            get {
                return ResourceManager.GetString("StepSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basic usage.
        /// </summary>
        internal static string TipsBasicUsage {
            get {
                return ResourceManager.GetString("TipsBasicUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JOG:  Double click in any point (or double tap).
        /// </summary>
        internal static string TipsJog {
            get {
                return ResourceManager.GetString("TipsJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard Shortcuts.
        /// </summary>
        internal static string TipsKeyboardShortcuts {
            get {
                return ResourceManager.GetString("TipsKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PAN:  Click and drag (or touch and drag).
        /// </summary>
        internal static string TipsPan {
            get {
                return ResourceManager.GetString("TipsPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ZOOM: Use mouse wheel (or two-finger gesture).
        /// </summary>
        internal static string TipsZoom {
            get {
                return ResourceManager.GetString("TipsZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom Auto (100%).
        /// </summary>
        internal static string TipsZoomAuto {
            get {
                return ResourceManager.GetString("TipsZoomAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom In   (+10%).
        /// </summary>
        internal static string TipsZoomIn {
            get {
                return ResourceManager.GetString("TipsZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom Out  (-10%).
        /// </summary>
        internal static string TipsZoomOut {
            get {
                return ResourceManager.GetString("TipsZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This file type is not supported..
        /// </summary>
        internal static string UnsupportedFiletype {
            get {
                return ResourceManager.GetString("UnsupportedFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the buffer is blocked, it is because there was some communication problem with your engraver. If you press &quot;OK&quot; LaserGRBL will ignore the full buffer and send the next commands. If this happens often, you should try to understand the causes of this problem.
        ///Click &quot;?&quot; for more information..
        /// </summary>
        internal static string WarnBufferStuckUnlockText {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unlock buffer.
        /// </summary>
        internal static string WarnBufferStuckUnlockTitle {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centerline option is not compatible with your PC.
        ///64bit OS is needed!.
        /// </summary>
        internal static string WarnCenterline64bit {
            get {
                return ResourceManager.GetString("WarnCenterline64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line2Line option is not compatible with your engraver or with your configuration. PWM-able laser is needed, and PWM support should be enabled in LaserGRBL settings..
        /// </summary>
        internal static string WarnLine2LinePWM {
            get {
                return ResourceManager.GetString("WarnLine2LinePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string WarnMessageBoxHeader {
            get {
                return ResourceManager.GetString("WarnMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have set negative offsets, but your engraver is set to use positive space with soft limit alarm enabled ($20=1).
        ///
        ///This could generate a soft-limit error. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitNS {
            get {
                return ResourceManager.GetString("WarnSoftLimitNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have set a size and offset that makes the job larger than the workspace configured in your engraver ({0}mm x {1}mm).
        ///Grbl Parameters $130 and $131.
        ///
        ///This could generate a soft-limit error or the machine could crash into the axes boundary. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitOOB {
            get {
                return ResourceManager.GetString("WarnSoftLimitOOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job boundary confirmation.
        /// </summary>
        internal static string WarnSoftLimitTitle {
            get {
                return ResourceManager.GetString("WarnSoftLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Freely assigning the width and height of the work can lead to distortion of the image. Do you want to continue?.
        /// </summary>
        internal static string WarnUnlockProportionText {
            get {
                return ResourceManager.GetString("WarnUnlockProportionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string WarnUnlockProportionTitle {
            get {
                return ResourceManager.GetString("WarnUnlockProportionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;M4 Dynamic Laser Power Mode&quot; has been set, but your engraver doesn&apos;t seem to support it.
        ///Only engravers with grbl version &gt;= 1.1 with &quot;laser mode&quot; enabled ($32=1) can take advantage of M4 option..
        /// </summary>
        internal static string WarnWrongLaserMode {
            get {
                return ResourceManager.GetString("WarnWrongLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string WarnWrongLaserModeTitle {
            get {
                return ResourceManager.GetString("WarnWrongLaserModeTitle", resourceCulture);
            }
        }
    }
}
