//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserGRBL.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click here to add custom buttons.
        /// </summary>
        internal static string AddCustomButtonsHint {
            get {
                return ResourceManager.GetString("AddCustomButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort current job?.
        /// </summary>
        internal static string BoxAbortProgramConfirm {
            get {
                return ResourceManager.GetString("BoxAbortProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic update failed!
        ///Please manually download the new version from lasergrbl site..
        /// </summary>
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update require administrator privilege!.
        /// </summary>
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update result.
        /// </summary>
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success!.
        /// </summary>
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some changes that have not been applied.
        ///Do you want to rewrite the configuration?.
        /// </summary>
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes detected!.
        /// </summary>
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to device.
        /// </summary>
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide GCode commands.
        /// </summary>
        internal static string BoxCustomButtonPleaseGCodeText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseGCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide tooltip text.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing field.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipTitle {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected button?.
        /// </summary>
        internal static string BoxDeleteCustomButtonText {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete custom button.
        /// </summary>
        internal static string BoxDeleteCustomButtonTitle {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting config!.
        /// </summary>
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist!.
        /// </summary>
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config exported successfully!.
        /// </summary>
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file!.
        /// </summary>
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config imported with {1} errors!.
        /// </summary>
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config imported successfully!.
        /// </summary>
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import custom button.
        /// </summary>
        internal static string BoxImportCustomButtonCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove actual buttons? Select yes to remove, no to keep..
        /// </summary>
        internal static string BoxImportCustomButtonClearText {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string BoxImportCustomButtonrCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading config!.
        /// </summary>
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing cached values....
        /// </summary>
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config readed successfully!.
        /// </summary>
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes... nothing to write!.
        /// </summary>
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config written with {1} errors!.
        /// </summary>
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config written successfully!.
        /// </summary>
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string BtnConnectTT {
            get {
                return ResourceManager.GetString("BtnConnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string BtnDisconnectTT {
            get {
                return ResourceManager.GetString("BtnDisconnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit button.
        /// </summary>
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove button.
        /// </summary>
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer in progress. Disconnect anyway?.
        /// </summary>
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer in progress. Exit anyway?.
        /// </summary>
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        internal static string FirmwareRequireRestart {
            get {
                return ResourceManager.GetString("FirmwareRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is required to apply Firmware type changes. Restart now?.
        /// </summary>
        internal static string FirmwareRequireRestartNow {
            get {
                return ResourceManager.GetString("FirmwareRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_greece {
            get {
                object obj = ResourceManager.GetObject("flag_greece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpticalCorrect.
        /// </summary>
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleAverage.
        /// </summary>
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightAverage.
        /// </summary>
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth (HQ Bicubic).
        /// </summary>
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp (NearestNeighbor).
        /// </summary>
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require application restart, restart now?.
        /// </summary>
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time:.
        /// </summary>
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Time:.
        /// </summary>
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open a new file now..
        /// </summary>
        internal static string MsgboxCannotOpenFileNow {
            get {
                return ResourceManager.GetString("MsgboxCannotOpenFileNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that the current position is no longer known by Grbl.
        ///Without the Homing Procedure ($H) the result may not be reliable.
        ///Continue anyway?.
        /// </summary>
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown position.
        /// </summary>
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string SpeedSliderToolTip {
            get {
                return ResourceManager.GetString("SpeedSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step:.
        /// </summary>
        internal static string StepSliderToolTip {
            get {
                return ResourceManager.GetString("StepSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not supported..
        /// </summary>
        internal static string UnsupportedFiletype {
            get {
                return ResourceManager.GetString("UnsupportedFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centerline option is not compatible with your PC.
        ///64bit OS is needed!.
        /// </summary>
        internal static string WarnCenterline64bit {
            get {
                return ResourceManager.GetString("WarnCenterline64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line2Line option is not compatible with your engraver or with your configuration. PWM-able laser is needed, and PWM support should be enabled in LaserGRBL settings..
        /// </summary>
        internal static string WarnLine2LinePWM {
            get {
                return ResourceManager.GetString("WarnLine2LinePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarnMessageBoxHeader {
            get {
                return ResourceManager.GetString("WarnMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have set negative offsets, but your engraver is set to use positive space with soft limit alarm enabled ($20=1).
        ///
        ///This could generate a soft-limit error. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitNS {
            get {
                return ResourceManager.GetString("WarnSoftLimitNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have set a size and offset that makes the job larger than the workspace configured in your engraver ({0}mm x {1}mm).
        ///Grbl Parameters $130 and $131.
        ///
        ///This could generate a soft-limit error or the machine could crash into the axes boundary. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitOOB {
            get {
                return ResourceManager.GetString("WarnSoftLimitOOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job boundary confirmation.
        /// </summary>
        internal static string WarnSoftLimitTitle {
            get {
                return ResourceManager.GetString("WarnSoftLimitTitle", resourceCulture);
            }
        }
    }
}
